version: '3.5'
services:
  app:
    image: ghcr.io/ddbj/sapporo-web:1.0.4
    container_name: sapporo-web
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=1121
      # - SAPPORO_URL_PREFIX=/prefix/
      # - SAPPORO_LOAD_PRE_REGISTERED_SERVICES=true # true or false
    ports:
      - 0.0.0.0:1121:1121
    restart: on-failure
    working_dir: /app
    command: ['yarn', 'start']
    networks:
      - sapporo

networks:
  sapporo:
    name: sapporo-network
